sudo: required
language: python
services: docker
before_install:
  - docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo DATABASE_URL=$DATABASE_URL >> .env
  - docker-compose up --build -d
script:
  - docker-compose exec web python manage.py test
# deploy:
#   provider: script
#   script: heroku container:login;
#     heroku container:push web --recursive Dockerfile.prod
#     heroku container:release web
