sudo: required

language: python

services: docker

before_install:
  - docker-compose -f docker-compose.yml up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
  - docker-compose -f docker-compose.yml exec web python manage.py test

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: heroku login;
#     heroku git:remote --app $HEROKU_APP_NAME;
#     git push heroku master;
#     heroku run python manage.py migrate;
#   on:
#     branch: master

deploy:
  provider: script
  skip_cleanup: true
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f docker/web/Dockerfile .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app registry.heroku.com/$HEROKU_APP_NAME/web gunicorn config.wsgi:application --bind 0.0.0.0:8000
  on:
    branch: master
