sudo: required
language: python
services: docker
before_install:
  - heroku update
  - docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
  - heroku git:remote -a $HEROKU_APP_NAME
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo DATABASE_URL=$DATABASE_URL >> .env
  - docker-compose up --build -d
script:
  - docker-compose exec web python manage.py test

deploy:
  provider: script
  skip_cleanup: true
  script: heroku container:login;
    heroku container:push web --recursive --app $HEROKU_APP_NAME;
    heroku container:release web --a $HEROKU_APP_NAME;
    heroku run python manage.py migrate;
  branch: master
