sudo: required

language: python

services: docker

before_install:
  - heroku update
  - docker-compose -f docker-compose.yml up --build -d
  # - heroku auth:token
  # - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com
  # - export HEROKU_API_KEY='b67b21cf-0f7d-4273-88d8-062c5d7ed73b'

script:
  - docker-compose -f docker-compose.yml exec web python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: GNcgHsz1CfrVU6G3Kh8YUDr2rPAl1joLIYNpyTr4oVCQ7VQsOWsOJYswwX4U04Kb+ai++p0B64gtzr7wt7L00+n3IbspEY7qkotS7XjAMDnnLyriunuJs24z8sIg/kTAJ1dmouroyDaOBRnR4medTDEBzNt7i+8Ntp4BvpWNGxwXFNYg3R+KMNejTu8SbKi6z5iGwaGr1xK/f12B704wlcAbNTJ+s3dbpKrCkuoli+1GRxk1M2hZpRqZRPyic9F3btfT0Y5s/wKdlZLv4rLrMwbQY2bHOn8q/HS20I3hFfjpxS7enmUrzxR1IeHV0GCTvfVrlQRBT/WqvXpZiUL1o3zw1fo+e/5b/5Rm7l8TQ8rTAjmwa+J19N1wv5Fo5A4cjr3xyg9FmBoDsMpJ+LoFPZ0LsEeisUBGDErsNmpN/bucCRkX/+aOpK1T5GYISybekl+oGYCA+Hr2lpKnEeaFdUJ8pIQJ38t2R7F4ALHGWCeqlgRF9qorHFIwvgNLkjKO4b52G4wWu3yYjDid3jxBq+Jnnr7dezwtwCU+Rt0q2b5cLQRbDq7hWTvnAsGWjJ/unm6RzJDJ2j8guwTBMuz3Y5uRaqDouFqXWirPKgJIcQxHvoZ1qjd0djx7ZxJOaCyQczNQfUzhVbVcM+n9UWMdMy3m4tXquQKS8PdTQgBaTPs=b
  skip_cleanup: true
  app: docker-django-heroku
  run:
    - heroku run python manage.py migrate
  on:
    branch: master
# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#     docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile .;
#     docker push registry.heroku.com/$HEROKU_APP_NAME/web;
#     heroku run --app registry.heroku.com/$HEROKU_APP_NAME/web python manage.py migrate
#   on:
#     branch: master
