sudo: required
language: python
services: docker
before_install:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo DATABASE_URL=$DATABASE_URL >> .env
  - docker-compose up --build -d
script:
  - docker-compose exec web python manage.py test
