sudo: required
language: python
services: docker
before_install:
  - heroku update
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - docker-compose -f docker-compose.prod.yml up --build -d
script:
  - docker-compose -f docker-compose.prod.yml exec web python manage.py test
deploy:
  provider: heroku
  api_key:
  skip_cleanup: true
  app: docker-django-heroku
  run:
    - heroku run python manage.py migrate
  on:
    branch: master
