sudo: required

language: python

services: docker

before_install:
  - heroku update
  - docker-compose -f docker-compose.yml up --build -d
  # - heroku auth:token
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com
  - heroku info

script:
  - docker-compose -f docker-compose.yml exec web python manage.py test
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: heroku login;
#     heroku git:remote --app $HEROKU_APP_NAME;
#     git push heroku master;
#     heroku run python manage.py migrate;
#   on:
#     branch: master
deploy:
  provider: script
  skip_cleanup: true
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app registry.heroku.com/$HEROKU_APP_NAME/web python manage.py migrate
  on:
    branch: master
