version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    environment:
      - SECRET_KEY='@mo2+rki#*%^p@z86#)6^u*g+07+dor-_(&hszdr9ys2qxwjx5'
    command: >
      bash -c "python manage.py migrate &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000 "
    tty: true
    stdin_open: true
