version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    command: >
      bash -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    tty: true
    stdin_open: true
