version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    environment:
      - SECRET_KEY=$SECRET_KEY
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    tty: true
    stdin_open: true
