version: "3"

volumes:
  db_data:

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    tty: true
    stdin_open: true

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    tty: true
    stdin_open: true
    depends_on:
      - db
