version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    environment:
      - SECRET_KEY=$SECRET_KEY
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    tty: true
    stdin_open: true
