version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    environment:
      - SECRET_KEY=$SECRET_KEY
      - HEROKU_API_KEY=$HEROKU_API_KEY
    command: >
      bash -c "yes | travis && yes | travis encrypt $HEROKU_API_KEY --add deploy.api_key && python manage.py migrate"
    tty: true
    stdin_open: true
